parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    impliedStrict: true

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended

plugins:
  - jest
  - dependencies

env:
  es6: true
  commonjs: true
  jest/globals: true
  browser: true
