# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - add_ssh_keys

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: |
            npm run coverage
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              npm run coverage:record;
            fi

      - run:
          name: Docs
          command: |
            npm run docs:build
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              git config --global user.email "$GIT_AUTHOR_EMAIL";
              git config --global user.name "$GIT_AUTHOR_NAME";
              npm run docs:publish;
            fi
